#!/bin/bash

# Locate ourselves
#THIS_DIR=$(realpath $BASH_SOURCE) # Not a command on OSX.
THIS_DIR=$(dirname $BASH_SOURCE) # We've been sourced so we can't use $0.
source ${THIS_DIR}/logging
source ${THIS_DIR}/help
alias help="_help"

function command_log() {
    echo "I am a bash function for commando"
}
