#!/bin/bash

# Use the value of the SLACK_TEAM_ID environment variable to look up the
# app API key for that workspace.
function slack_api_key() {
    TEAM_ID=${SLACK_TEAM_ID:-TEAM_ID_NOT_SET}
    SECRET_ID="integrations/slack/${TEAM_ID}"
    SECRET_RESPONSE="`aws secretsmanager get-secret-value --secret-id $SECRET_ID 2>&1`"
    if [ $? -ne 0 ]; then
        error $SECRET_RESPONSE
        echo ""
    else
        # Parse the JSON string into an object and return the key.
        echo $SECRET_RESPONSE | jq '.SecretString' | jq 'fromjson | .app_api_key' | tr -d '"'
    fi
}

# Lifted from https://newfivefour.com/unix-urlencode-urldecode-command-line-bash.html
urlencode() {
    # urlencode <string>

    local length="${#1}"
    for (( i = 0; i < length; i++ )); do
        local c="${1:i:1}"
        case $c in
            [a-zA-Z0-9.~_-]) printf "$c" ;;
            *) printf '%s' "$c" | xxd -p -c1 |
                   while read c; do printf '%%%s' "$c"; done ;;
        esac
    done
}
